### ISSUE TITLE
图片适配

### ISSUE THREAD

**Issue by mclmdream** [MegatronKing/SVG-Android#5]
同一张图片在小屏幕和大屏幕上不能适配

**Comment by MegatronKing** [comment]
你好！图片的尺寸单位使用的是dp，支持不同分辨率适配的。如果真有适配问题，希望能具体描述一下，方便排查原因。

**Comment by mclmdream** [comment]
就是说比如一张图片在小屏幕上显示宽度为小屏幕的一半，在大屏幕上显示宽度也显示大屏幕的一半

**Comment by MegatronKing** [comment]
Android图片适配是一般都是根据屏幕dpi适配，比如drawable-hdpi、drawable-xhdpi这些，而不是根据屏幕尺寸适配。相同dpi的屏幕，尺寸大小不一定相同，但是这个一般是不考虑的。比如你在layout布局文件适配，尺寸单位一般都用dp、sp，这样适配足矣，除非特殊图片才用计算屏幕尺寸来适配。所以，你所说的尺寸适配，不管用不用SVG-Android框架都是无法自动适配，唯一的方法就是依靠代码计算。
