### ISSUE TITLE
解析出的Renderer类过大

### ISSUE THREAD

**Issue by bnndy** [MegatronKing/SVG-Android#7]
如果要显示大的SVG图，比如一两百K的，会出现解析出的Renderer类中的render方法过大，超出JVM对方法大小65535的限制的情况

**Comment by MegatronKing** [comment]
首先，非常抱歉出现这样的问题。在测试的时候，确实也遇到过几百k的矢量图片，由于Path中的数据异常庞大导致render方法大小超出编译器限制。考虑下来有两点：第一点，几百k的矢量图片即使render方法大小不超过限制，其图片渲染性能相比同样的PNG位图会慢非常非常多，这种情况建议直接使用PNG图；第二点，几百k的矢量图可能是由不正确的设计导致的，建议重新设计矢量图，另外可以尝试使用[SVGOMG](https://jakearchibald.github.io/svgomg/) 优化压缩下。

**Comment by bnndy** [comment]
你好，由于SVG比png的独有的优势，使得我们决定采用svg来显示某些场景下的图片，因为场景特殊，在使用您的代码解析之前，已经用SVGOMG 来压缩过了，但SVG文件依然有一两百K的大小，进而出现了render方法过大的问题。能否考虑一下，在构建render方法时，若遇到大的SVG，将render方法拆成几个小的子方法。

**Comment by MegatronKing** [comment]
这个建议很不错，非常感谢。我加到下个版本中，尽快更新发布。

**Comment by bnndy** [comment]
谢谢大神！十分期待您的更新，越快越好，万分感谢。

**Comment by MegatronKing** [comment]
抱歉有点晚，1.3.7版本已更新，jcenter已同步
