### ISSUE TITLE
是否可以由svg文件生成vector时直接将fillColor设置为 @color/icon_color

### ISSUE THREAD

**Issue by busyStone** [MegatronKing/SVG-Android#8]
在项目中是直接使用 svg 文件生成 xml的，但是 svg 文件的默认颜色不一致，想借助 icon_color 统一设置，所以，有没有办法在生成的之后直接将 fillColor设置为 @color/icon_color

**Comment by MegatronKing** [comment]
抱歉，目前不支持，只能手动修改。
