### ISSUE TITLE
自定义空间，svg 图标绘制位置错误

### ISSUE THREAD

**Issue by busyStone** [MegatronKing/SVG-Android#9]
自定义的 switch 控件，使用 svg 图标，绘制的时候发现图标一直从父控件的左上角开始绘制（预览正确）。
问题应该是下边 SVGDrawable.java 中代码导致

![image](https://cloud.githubusercontent.com/assets/1464948/24092153/706285c0-0d87-11e7-963c-7cbb993b9670.png)

现在是在自定义控件中调用 Drawable.Draw(canvas) 之前先进行 canvas.translate，这样结果是正确的（预览错误）。

想请教的是，这个 translate 理论上应该在哪里调用？

**Comment by MegatronKing** [comment]
请问是否可以提供下svg内容，方便排查下问题

**Comment by MegatronKing** [comment]
抱歉，这是个1.3.1版本的BUG。绘制SVG的Bound是mTmpBounds而不是Drawable的Bounds（当然，如果不对Drawable的Bounds做改变，这两个Bounds地值应该是一样的）。SVG绘制之前会将mTmpBounds偏移到控件的左上角(0, 0)，如果Drawable的Bounds不是从控件(0, 0)开始，确实就出现问题了。如果你能修改源码的话，把final int saveCount = canvas.save();和canvas.translate(mTmpBounds.left, mTmpBounds.top);这两句移到needMirroring前面。

**Comment by busyStone** [comment]
现在是在自定义控件里修改了。库已经很好用了，多谢！
